person_auction/urls.py
from django.contrib import admin
from django.urls import path, include

from person_auction import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name="home"),
    path('service/', include('service.urls'))
]

service/urls.py
from django.urls import path

from service import views

app_name = 'service'
urlpatterns = [

    path('auction/registration', views.AuctionRegistrationView.as_view(), name="auction_registration"),
    path('auction/list', views.AuctionRegistrationListView.as_view(), name="auction_registration_list"),

]

mgr/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
class Account(models.Model):
    fs = FileSystemStorage(location='media/images/', base_url='/media/images/')
    user = models.ForeignKey('auth.User', blank=False, on_delete=models.CASCADE, related_name='user_account')
    name = models.CharField(max_length=10, blank=True, null=True)
    nickName = models.CharField(max_length=10, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    thumbNail = models.ImageField(null=True, blank=True, storage=fs)
    class Meta:
        db_table = 'mgr_account'

class AuctionCategory(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'mgr_auction_category'

service/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
class AuctionRegistration(models.Model):
    lowestBid = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=0)
    dueDate = models.DateTimeField(null=True, blank=True)
    title = models.CharField(max_length=30, null=True, blank=True)
    explain = models.TextField(null=True, blank=True)
    categoryName = models.CharField(max_length=30, null=True, blank=True)
    account = models.ForeignKey('mgr.Account', blank=True,null=True, on_delete=models.SET_NULL, related_name='user_auction_registration')
    category = models.ForeignKey('mgr.AuctionCategory', blank=True,null=True, on_delete=models.SET_NULL,
                                related_name='category_auction_registration')
    class Meta:
        db_table = 'service_auction_registration'

class AuctionRegiImg(models.Model):
    fs = FileSystemStorage(location='media/images/', base_url='/media/images/')
    img = models.ImageField(null=True, blank=True, storage=fs)
    auction_regi = models.ForeignKey('AuctionRegistration', blank=False, on_delete=models.CASCADE,
                                related_name='auction_regi_img')
    class Meta:
        db_table = 'service_auction_regi_img'

mgr/forms.py
from django import forms

from mgr.validators import phonenumber_validator, tel_validator


class SignUpForm(forms.ModelForm):
    uid = forms.CharField(widget=forms.TextInput, label='아이디')
    password = forms.CharField(widget=forms.PasswordInput, label='패스워드 입력')
    password1 = forms.CharField(widget=forms.PasswordInput, label='패스워드 재입력')
    email = forms.EmailField(widget=forms.EmailInput, label='이메일')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mobile'].validators.append(phonenumber_validator)
        self.fields['tel'].validators.append(tel_validator)


    def clean(self):
        cleaned_data = super().clean()
        id = cleaned_data.get('uid')
        if Account.objects.filter(user__username=id):
            raise forms.ValidationError("동일한 아이디가 존재합니다.")
        email = cleaned_data.get('email')
        if Account.objects.filter(user__email=email):
            raise forms.ValidationError("동일한 이메일이 존재합니다.")
        password = cleaned_data.get('password')
        password1 = cleaned_data.get('password1')
        if password is None or password1 is None:
            pass
        else:
            if password != password1:
                 raise forms.ValidationError("패스워드가 일치하지 않습니다.")

    class Meta:
        model = Account
        fields = ['name','branch','brand', 'businessLicenseNumber', 'mobile','tel','nateOnId','depositor']
        widgets = {
            'name': forms.TextInput,
            'branch': forms.Select,
            'brand': forms.TextInput,
            'businessLicenseNumber': forms.NumberInput,
            'mobile': forms.NumberInput,
            'tel': forms.NumberInput,
            'nateOnId': forms.TextInput,
            'depositor' : forms.TextInput,

        }
        labels = {
            'name': '이름',
            'branch': '지점',
            'brand': '브랜드',
            'businessLicenseNumber': '사업자번호',
            'mobile': '핸드폰',
            'tel': '매장번호',
            'nateOnId': '네이트온아이디',
            'depositor': '입금자',
        }

service/forms.py
from django import forms

from service.models import AuctionRegistration


class AuctionRegistrationForm(forms.ModelForm):
    class Meta:
        model = AuctionRegistration
        exclude = ['account', 'categoryName']
        widgets = {
            "lowestBid": forms.NumberInput,
            "dueDate": forms.DateTimeInput,
            "title ": forms.TextInput,
            "explain": forms.Textarea,
            "category": forms.Select
        }
        label = {
            "lowestBid": "최저입찰가",
            "dueDate": "마감일",
            "title ": "제목",
            "explain": "내용",
            "category": "카테고리"
        }

mgr/views.py
from django.shortcuts import render

# Create your views here.

person_auction/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return context

service/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView, ListView

from service.forms import AuctionRegistrationForm
from service.models import AuctionRegistration


class AuctionRegistrationView(FormView):
    template_name = 'service/auction_registration.html'
    form_class = AuctionRegistrationForm
    success_url = reverse_lazy('home')
    def get(self, request, *args, **kwargs):
        context = super().get_context_data()

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = super().get_context_data()
        ar_form = AuctionRegistrationForm(request.POST)
        if ar_form.is_valid():
            return self.form_valid(ar_form)
        return self.render_to_response()

    def form_valid(self, form):
        this_form = form.save(commit=False)
        #this_form.account = self.request.user
        name = this_form.category.name
        this_form.categoryName = name
        this_form.save()
        #this_form.save_m2m()
        return super().form_valid(form)

class AuctionRegistrationListView(TemplateView):
    template_name = 'service/auction_list.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['model'] = AuctionRegistration.objects.all()
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>
<body>
<div class="row">
    <div class="col-12 col-md-12 col-sm-12">
        <div class="bs-component">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'service:auction_registration_list' %}">경매등록리스트</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'service:auction_registration' %}">경매등록</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sign Up</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>
    </div>
</div>
<div id="main">
    {% block main %}

    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

templates/service/auction_list.html
{% extends 'base.html' %}
   {% block main %}
       <table class="table table-striped">
       <colgroup>

       </colgroup>
       <thead>
       <tr>
      <th></th>
           <th></th>
           <th></th>

           <th></th><th></th>


       </tr>
       </thead>
       <tbody>
       {% for obj in model %}
       <tr>
       <td>{{ obj.lowestBid }}</td>
           <td>{{ obj.dueDate }}</td>
           <td>{{ obj.title }}</td>
           <td>{{ obj.explain }}</td>
           <td>{{ obj.categoryName }}</td>
       </tr>
       {% endfor %}
       </tbody>
       </table>
    {% endblock %}

templates/service/auction_registration.html
{% extends 'base.html' %}
   {% block main %}
       <form action="{% url 'service:auction_registration'%}" method="post">
       {% csrf_token %}
     {{ form.as_p }}
       <button type="submit" class="btn btn-info">저장</button>
       </form>
    {% endblock %}